### ISSUE TITLE
Error when trying to run the server for the first time

### ISSUE THREAD

**Issue by silvernode** [hakt0r/nuu#2]
create: creating file db/InventoryDB.db failed with status 2 (No such file or directory)
create: creating file db/UserDB.db failed with status 2 (No such file or directory)
/home/mollusk/nuu/build/server.js:9804
      this.set(name, data);
           ^

TypeError: XScale db not open
    at XScale.create (/home/mollusk/nuu/build/server.js:9804:12)
    at Object.$tag.db (/home/mollusk/nuu/build/server.js:9775:12)
    at Object.<anonymous> (/home/mollusk/nuu/build/server.js:10013:8)
    at Object.<anonymous> (/home/mollusk/nuu/build/server.js:10550:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by silvernode** [comment]
Solved by creating the db dirextory manually in the nuu project root dirextory. Feel free to close this issue if you have no questions/

**Comment by hakt0r** [comment]
Thanks alot for trying :) This will be fixed upon the next release, i promise... sorry for taking my time, this is a once-a-year-a-little-bit project for me right now....

**Comment by hakt0r** [comment]
fixed
